version: '3.4'

services:
   mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped    
   project_api:
    environment: 
     DBCONNECTION: "mssql"
    depends_on: [mssql]
    build:
      context: .
    ports:
      - 8080:80